resource "local_file" "ansible_vars" {
  content         = <<-EOF
# Ansible inventory containing variable values from Terraform.
# Generated by Terraform.
---
domain_name: mayurov.ru
mysql_wp_database: wordpress
mysql_wp_user: wordpress
mysql_wp_password: wordpress
mysql_master: ${yandex_compute_instance.my-sql[0].hostname}
mysql_master_ip: ${yandex_compute_instance.my-sql[0].network_interface.0.ip_address}
mysql_slave_ip: ${yandex_compute_instance.my-sql[1].network_interface.0.ip_address}
mysql_host: ${yandex_compute_instance.my-sql[0].network_interface.0.ip_address}
gitlab_ip: ${yandex_compute_instance.gitlab.network_interface.0.ip_address}
app_server_ip: ${yandex_compute_instance.app.network_interface.0.ip_address}
monitoring_ip: ${yandex_compute_instance.monitoring.network_interface.0.ip_address}
nginx_ip: ${yandex_compute_instance.nginx1.network_interface.0.ip_address}
    EOF
  filename        = "../ansible/group_vars/all.yml"
  file_permission = "0644"
  
}