variable "ansible_user" {
    type = string
    default = "ubuntu"
}
resource "local_file" "inventory" {
  content         = <<-EOF
# Ansible inventory containing variable values from Terraform.
# Generated by Terraform.
---
all:
  children:
    nginx_servers:
      hosts:
        ${yandex_compute_instance.nginx1.hostname}:
          ansible_host: ${yandex_compute_instance.nginx1.network_interface.0.nat_ip_address}
          ansible_user: ${var.ansible_user}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no"
    db:
      hosts:
        ${yandex_compute_instance.my-sql[0].hostname}:
          ansible_host: ${yandex_compute_instance.my-sql[0].network_interface.0.ip_address}
          ansible_user: ${var.ansible_user}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ${var.ansible_user}@${yandex_compute_instance.nginx1.network_interface[0].nat_ip_address}"
          cluster_role: 'master'
        ${yandex_compute_instance.my-sql[1].hostname}:
          ansible_host: ${yandex_compute_instance.my-sql[1].network_interface.0.ip_address}
          ansible_user: ubuntu
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ${var.ansible_user}@${yandex_compute_instance.nginx1.network_interface[0].nat_ip_address}"
          cluster_role: 'slave'
    wordpress:
      hosts:
        ${yandex_compute_instance.app.hostname}:
          ansible_host: ${yandex_compute_instance.app.network_interface.0.ip_address}
          ansible_user: ${var.ansible_user}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ${var.ansible_user}@${yandex_compute_instance.nginx1.network_interface[0].nat_ip_address}"
    gitlabs:
      hosts:
        ${yandex_compute_instance.gitlab.hostname}:
          ansible_host: ${yandex_compute_instance.gitlab.network_interface.0.ip_address}
          ansible_user: ${var.ansible_user}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ${var.ansible_user}@${yandex_compute_instance.nginx1.network_interface[0].nat_ip_address}"
    monitorings:
      hosts:
        ${yandex_compute_instance.monitoring.hostname}:
          ansible_host: ${yandex_compute_instance.monitoring.network_interface.0.ip_address}
          ansible_user: ${var.ansible_user}
          ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -J ${var.ansible_user}@${yandex_compute_instance.nginx1.network_interface[0].nat_ip_address}"
    EOF
  filename        = "../ansible/inventory.yml"
  file_permission = "0644"
  
}