---
- name: Install Nginx and letsencrypt
  hosts: nginx_servers
  roles: 
    - { role: intall-nginx-letsencrypt }
    - { role: install-nodeexporter }
 - name: install mySqlCluster
   hosts: db
   roles:
       - { role: install-mysql }
       - { role: install-nodeexporter }
 - name: install Wordpress
   hosts: wordpress
   roles:
       - { role: install-wordpress }
       - { role: install-gitlab-runner}
       - { role: install-nodeexporter }
 - name: install Gitlab
   hosts: gitlabs
   roles:      
     - { role: install-gitlab-server }
     - { role: install-nodeexporter }
- name: install monitoring
  hosts: monitorings
  roles:
    - { role: install-monitoring }
    - { role: install-nodeexporter }
#  tasks:
#    - name: install docker packeges
#      become: true
#      ansible.builtin.apt:
#        name: "{{ item }}"
#        state: latest
#        update_cache: yes
#      loop: 
#        - docker.io
#        - python3-docker
#    - name: run docker image Gitlab
#      become: true
#      community.docker.docker_container:
#        name: gitlab
#        hostname: gitlab
#        image: gitlab/gitlab-ce:latest
#        volumes:
#          - /srv/gitlab/config:/etc/gitlab
#          - /srv/gitlab/logs:/var/log/gitlab
#          - /srv/gitlab/data:/var/opt/gitlab
#        ports:
#          - "1022:22"
#          - "80:80"
#          - "4567:4567"
 #   - name: download gitlab runner           # Запихнуть в роль установки Wordpress
 #     ansible.builtin.get_url:   
 #       url: "https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_arm64.deb"
 #       dest: /tmp
#    - name: Install gitlab runner           # Установка gitlab-runner для автоматиского деплоя обновлений в репозитория
#      become: true
#      ansible.builtin.apt:   
#        deb: https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb
#    - name: add gitlab-runner to sudo       # Добавление пользователя gitlab-runner в группу sudo
#      become: true
#      ansible.builtin.user:
#        name: gitlab-runner
#        groups: "sudo"
#        append: yes  
#    - name: sudo without password for gitlab runner   # Разрешить пользователю gitlab-runner запуск sudo без ввода пароля 
#      become: true
#      copy:
#        content: 'gitlab-runner ALL=(ALL) NOPASSWD: ALL'
#        dest: /etc/sudoers.d/gitlab_runner_nopasswd
#        mode: 0440

#gitlab-runner ALL=(ALL) NOPASSWD: ALL



#sudo docker run --detach \
#  --hostname gitlab.mayurov.ru \
#  --publish 443:443 --publish 80:80 --publish 1022:22 --publish 4567:4567 \
#  --name gitlab \
#  --restart always \
#  --volume /srv/gitlab-runner/config:/etc/gitlab-runner \
#  --volume /var/run/docker.sock:/var/run/docker.sock \
#  gitlab/gitlab-ce:latest

#- name: install mySqlCluster
#  hosts: db
#  roles:
#      - { role: install-mysql }
#- name: install Wordpress
#  hosts: wordpress
#  roles:
#      - { role: install-wordpress }
#      - { role: install-gitlab-runner}
#- name: test
#  hosts: localhost
#  tasks:
#    - name: task1
#      debug:
#        #msg: qwe
#        msg: "{{ item.ip }} {{ item.hostname}}"
#      loop: "{{ test }}"
        