---
- name: Install Nginx and letsencrypt     
  hosts: nginx_servers
  roles: 
    - { role: intall-nginx-letsencrypt }
    - { role: install-nodeexporter }
 - name: install mySqlCluster
   hosts: db
   roles:
       - { role: install-mysql }
       - { role: install-nodeexporter }
 - name: install Wordpress
   hosts: wordpress
   roles:
       - { role: install-wordpress }
       - { role: install-gitlab-runner}
       - { role: install-nodeexporter }
 - name: install Gitlab
   hosts: gitlabs
   roles:      
     - { role: install-gitlab-server }
     - { role: install-nodeexporter }
- name: install monitoring
  hosts: monitorings
  roles:
    - { role: install-monitoring }
    - { role: install-nodeexporter }
